
# This workflow will install Python dependencies, run tests and lint with a single version of Python
# 
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actionsname: JavSEnoid

# Controls when the action will run. 
name: JarCI

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: '1 00 * * *'
#env:
#  TZ: "Asia/Tokyo"

jobs:
  SetupClean:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write
    strategy:
      matrix:
        scan: [opened, reopened, synchronize, build]
      fail-fast: false 
    env:
        JOB: ${{ matrix.go }}

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
          workflow_id: ${{ github.event.workflow.id }}
          ignore_sha: true
      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 3
  # ============================= https://upload.wikimedia.org/wikipedia/commons/8/8f/Nuvola_mimetypes_java_jar.png
  JavaInfo:
    runs-on: ubuntu-latest
    needs: [SetupClean]
    strategy:
      matrix:
        scan: [JDK]
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Info
      run: python generate.py
    - name: Commit
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add .
        git commit -am "Update README"
        git push --all -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  ScanSetup:
    runs-on: ubuntu-20.04

    needs: [JavaInfo, SetupClean]
    timeout-minutes: 260
    strategy:
      matrix:
        scan: [JDK, J2SE]
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: 🎈ScanSetup
      run: java -jar fastjson-1.2.24.jar

  Download:
    runs-on: ubuntu-18.04
    needs: [JavaInfo, SetupClean, ScanSetup]
    timeout-minutes: 260
    strategy:
      matrix:
        scan: [J2SE, JDK]
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: 🌈 Download
      run: |
        ls
        java -jar commons-codec-1.9.jar

  Build:
    runs-on: ubuntu-16.04
    needs: [JavaInfo, SetupClean, ScanSetup, Download]
    timeout-minutes: 260
    strategy:
      matrix:
        scan: [JavSE, Jdk]
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: 🤞 Build
      run: java -jar generateUser.jar


  Compile:
    runs-on: ubuntu-latest
    needs: [JavaInfo, SetupClean, ScanSetup, Download, Build]
    timeout-minutes: 260
    strategy:
      matrix:
        scan: [JDK, Jse]
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: ✨ Compile 
      run: java -jar httpclient-4.5.2.jar

  execute:
    runs-on: ubuntu-18.04
    needs: [JavaInfo, SetupClean, ScanSetup, Download, Build, Compile]
    timeout-minutes: 260
    strategy:
      matrix:
        scan: [JDK, JavaLTS]
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: 🚀 execute 
      run: java -jar scanuser.jar

